name: Build Jekyll and Deploy to Firebase Beta

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Beta
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --config _config.yml,_config.beta.yml"

    - name: Deploy Beta
      if: github.ref == 'refs/heads/beta'
      uses: doonstore/firebase-deploy@v1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: 'beta'
